### ISSUE TITLE
[bug] 在使用插件加载了一些脚本后出现了官方原版表情加载失败的问题

### ISSUE THREAD

**Issue by Minesaudade** [PRO-2684/Scriptio#11]
![列表截图](https://github.com/user-attachments/assets/8f48fb73-c71e-4f68-8109-99c34486f480)
![插件列表](https://github.com/user-attachments/assets/3605395a-b73f-4b80-a7a8-e79d5a804c09)

以上为所用的脚本和插件截图

出现的问题为
![bugjietu2](https://github.com/user-attachments/assets/42dbde4f-00dc-4b43-aacb-74f6af8e8ae3)
![bug发送表情3](https://github.com/user-attachments/assets/c4021ae1-450a-4710-9904-f2384232e2be)
![bug截图1](https://github.com/user-attachments/assets/48a53b23-5126-4c2e-ac6d-b3f22ba0888d)
![bug重载消息](https://github.com/user-attachments/assets/80b03baf-5b1c-4d68-b499-3d9e7d145e93)

表情列表中还亮着的可以发送 
发送出去后 
重启QQ 
刚才使用的官方表情就会无法加载，并且列表里该表情变成转圈圈，自定义的表情包可以加载

昨天用了脚本加载器之后出现的问题 推测是privacio 但是在关闭所有脚本以及脚本加载器插件也并没有恢复
于是又尝试关闭了所有插件 包括LiteloaderQQNT 都没恢复，除非在QQNT启动项里添加的LiteloaderQQNT启动项删除，才恢复显示，
于是又怀疑是新版本LiteloaderQQNT或者新版本QQ的问题 但是在卸载QQ和插件用回旧版本之后还是没有恢复
实在没有办法所以来求助一下作者 旧版本QQ和旧版本插件此前都顺利运行 QQ版本是9.9.12-25493   旧版本LiteLoaderQQNT 为1.1.1

**Comment by PRO-2684** [comment]
先禁用此插件查看情况，若仍有此问题则是其它插件/llqqnt 本体的问题

**Comment by Minesaudade** [comment]
好的 感谢
