### ISSUE TITLE
无法查看调试信息

### ISSUE THREAD

**Issue by StoneFancy** [PRO-2684/Scriptio#16]
![aa96a2d14897777ebaaa814ec1f5e4f7](https://github.com/user-attachments/assets/fb4ec72f-4107-4c97-95af-d306186480ff)
![658b3ab4615f3712836d587edb73edc8](https://github.com/user-attachments/assets/87113341-594a-48bd-adc0-f66628001dfe)

我的脚本
![f8ac60880c6988b2cf489e09ac90e2f0](https://github.com/user-attachments/assets/75e988ce-a52b-4044-82a0-5911142ccef7)

![64223d18fa305718642e610d719c951e](https://github.com/user-attachments/assets/63e35564-9b9a-4743-978a-2069c12434dc)

我按照wiki中的示例编写了一个示例脚本，当我想要查看脚本输出的时候，什么也没有

**Comment by PRO-2684** [comment]
请指定 `@run-at`

**Comment by StoneFancy** [comment]
![ff31cca26569ef556e8632f645ee7412](https://github.com/user-attachments/assets/fd197d93-1944-4ef5-9b9b-776adcbc8722)
这样算是成功了嘛？但是为什么没有我打印的helloworld

**Comment by StoneFancy** [comment]
> 请指定 `@run-at`
![e076acdf0471f81ca7d50a55f276599c](https://github.com/user-attachments/assets/c02d46a5-97bc-4759-9668-774025b10672)
指定了run-at为main, chat后，powershell控制台还是没有输出,但是我装了另一个插件可以在F12的控制台里面看到这个

**Comment by StoneFancy** [comment]
> 请指定 `@run-at`
![13567968fb876007cf5d8b4928de80bf](https://github.com/user-attachments/assets/c114880d-803f-43a2-9c16-a00be124b570)
指定run-at依旧是什么没有

**Comment by StoneFancy** [comment]
> 请指定 `@run-at`

好了解决了，原来这个调试是要结合[chii-devtools](https://github.com/mo-jinran/chii-devtools/tree/v4) 插件
而且我没有调用log函数
![dfbdfac405f1ff0678c717c0d493228f](https://github.com/user-attachments/assets/49fb0660-8e65-4b57-939e-463d1cee5146)
![5c999db1f012a96cfc950bddab7b39e7](https://github.com/user-attachments/assets/8cf53e10-856e-41e2-9489-48ce117f76f9)
我已经在控制台成功输出了日志！！

**Comment by PRO-2684** [comment]
> > 请指定 `@run-at`
> 
> 好了解决了，原来这个调试是要结合[chii-devtools](https://github.com/mo-jinran/chii-devtools/tree/v4) 插件 而且我没有调用log函数 ![dfbdfac405f1ff0678c717c0d493228f](https://private-user-images.githubusercontent.com/53338920/390310329-49fb0660-8e65-4b57-939e-463d1cee5146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2OTUyNDIsIm5iZiI6MTczMjY5NDk0MiwicGF0aCI6Ii81MzMzODkyMC8zOTAzMTAzMjktNDlmYjA2NjAtOGU2NS00YjU3LTkzOWUtNDYzZDFjZWU1MTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA4MDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MDVlMGY2ZDliYTk5NWM0MjhiMjRkZDUzMzQwODQ1ODA0ZTZlYTcyOWUxZDVkNWU4NWE2NWM1YWE1NjNiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hiV9TW-5jnyU_ye4q84r0QV3pmA_jy_AXnUXTcKE8ak) ![5c999db1f012a96cfc950bddab7b39e7](https://private-user-images.githubusercontent.com/53338920/390310510-8cf53e10-856e-41e2-9489-48ce117f76f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2OTUyNDIsIm5iZiI6MTczMjY5NDk0MiwicGF0aCI6Ii81MzMzODkyMC8zOTAzMTA1MTAtOGNmNTNlMTAtODU2ZS00MWUyLTk0ODktNDhjZTExN2Y3NmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA4MDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YTA4OTk3NzJlZTNlZDdkODhkNzFhNTZkOTUzM2MzYjc0ZThhNGFjOWU2OTg4MDJmNTU4ZjM5N2MwNjY1NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7q3ndZOs8io_WEkV3a_mH_FxzxQV2p-g6IIdvR3jfRA) 我已经在控制台成功输出了日志！！

- 添加 `--enable-logging` 可以在命令行观察主进程输出以及渲染层输出
- 添加 `--scriptio-debug` 可以让此插件输出调试信息
- 若安装了 chii 并且无需调试 Scriptio，则无需添加任何参数
