### ISSUE TITLE
大佬能否加一个"消息连续显示"的脚本

### ISSUE THREAD

**Issue by LittleId** [PRO-2684/Scriptio#4]
类似这个https://github.com/ImZjm/LiteLoaderQQNT-Message-Show
更新LiteLoaderQQNT 1.0后，发现链接里的插件失效了，现在也没得用了，希望大佬可以开发下🤣🤣

**Comment by PRO-2684** [comment]
这个比较麻烦，你可以尝试用一下 [轻量工具箱](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools)
