### ISSUE TITLE
[BUG] 商店报错

### ISSUE THREAD

**Issue by vesugier** [PRO-2684/Scriptio#5]
![图片](https://github.com/PRO-2684/Scriptio/assets/66554786/bb7d8358-8fc5-44ab-aead-13afd2a9bd36)

### 版本信息
scriptio 1.1.3
liteloader 1.0.3
qqnt 9.9.7-21484
nodejs 18.18.2

**Comment by PRO-2684** [comment]
发生错误时的具体操作是？

**Comment by PRO-2684** [comment]
初步鉴定为插件商店引入的 GitHub 代理问题。下载失败的情况下请尝试手动下载安装脚本，同时也可以向插件商店提出 issue。
