### ISSUE TITLE
[bug] 启用开发者模式更新脚本会导致整个LiteLoader崩溃

### ISSUE THREAD

**Issue by QingFeng-awa** [PRO-2684/Scriptio#9]
![image](https://github.com/user-attachments/assets/c9dcef5c-70c1-4dbd-bbff-70660e2f85a3)
本体版本请见图片,插件版本1.3.4。
当我启用开发者模式并更新文件时,LiteLoader会直接崩溃。
具体症状表现为:更新文件后LiteLoader以及插件设置页直接消失。
我启用的所有脚本请看图片。
![image](https://github.com/user-attachments/assets/70de5d17-f895-41b3-bf9d-f664029416fe)

**Comment by PRO-2684** [comment]
偶发问题还是必定出现

**Comment by QingFeng-awa** [comment]
必定,我安装的所有样式都这样

**Comment by PRO-2684** [comment]
暂时无法复现，猜测是新版兼容性问题
可以考虑禁用此功能，更新脚本后双击“导入脚本...”来手动重载窗口

**Comment by Shapaper233** [comment]
我这边也会轻微出现，但是多次打开设置就可以临时修复
主界面也有概率所有插件注入丢失，我感觉是上游问题

**Comment by Shapaper233** [comment]
新版liteloader似乎已修复

**Comment by QingFeng-awa** [comment]
应该修了
没人发评论我都忘了这个issue了（
